### ISSUE TITLE
Add unit tests for failIfTrimmed use case

### ISSUE THREAD

**Issue by paazmaya** [paazmaya/grunt-trimtrailingspaces#10]
Currently tests are missing....

**Comment by kumarmj** [comment]
On `npm run lint`, there is warning

```
grunt-trimtrailingspaces/tasks/trimtrailingspaces.js
  29:81  warning  This function has too many statements (13). Maximum allowed is 10  max-statements

✖ 1 problem (0 errors, 1 warning)
```

I studied this issue, it looks need to un-comment these only
- https://github.com/paazmaya/grunt-trimtrailingspaces/blob/master/test/trimtrailingspaces_test.js#L82-L101
- https://github.com/paazmaya/grunt-trimtrailingspaces/blob/master/Gruntfile.js#L61-L70

Now problem is overriding `grunt.fail.warn` didn't worked
```javascript
grunt.fail.warn = function (msg, code) {
  test.equals(code, 6, 'Failed task specifies error code as defined in the task registration');
};
```

Secondly, as `force` option didn't worked as well
```javascript
grunt.option('force', true);
```

Error that appear on `npm test` is
```
Warning: The failIfTrimmed option is set to true. Use --force to continue.

Aborted due to warnings.
```

Worse is even tried `npm test --force`, then also aborted with same warning. I do not found any way to work-around please if I should know anything, let me know.

**Comment by paazmaya** [comment]
Thank you @kumarmj for looking at the issue!

**Comment by antonionoca** [comment]
hey @paazmaya @kumarmj, I added a test and fixed the eslint issue. Check the merge request :)
